name: VitalTpa
version: @version@
main: com.tamrielnetwork.vitaltpa.VitalTpa
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to teleport to each other.
commands:
  vitaltpa:
    description: "Main command"
    usage: "/vitaltpa tp/tphere <player>"
permissions:
  vitaltpa.tpa:
    description: "Permission to send request to teleport to others"
    default: op
  vitaltpa.tpahere:
    description: "Permission to send request to teleport others to you"
    default: op
  vitaltpa.tpyes:
    description: "Permission to accept teleport request"
    default: op
  vitaltpa.tpno:
    description: "Permission to deny teleport request"
    default: op