name: VitalTpa
version: @version@
main: com.tamrielnetwork.vitaltpa.VitalTpa
api-version: 1.17
authors: [ Leopold Meinel ]
description: Gives players the ability to teleport to each other.
commands:
  tpa:
    description: "Main command"
    usage: "/tpa <player>"
  tpahere:
    description: "Main command"
    usage: "/tpahere <player>"
  tpno:
    description: "Main command"
    usage: "/tpno"
  tpyes:
    description: "Main command"
    usage: "/tpyes"
  tpcancel:
    description: "Main command"
    usage: "/tpcancel"
permissions:
  vitaltpa.tpa:
    description: "Permission to send request to teleport to others"
    default: op
  vitaltpa.tpahere:
    description: "Permission to send request to teleport others to you"
    default: op
  vitaltpa.tpyes:
    description: "Permission to accept teleport request"
    default: op
  vitaltpa.tpno:
    description: "Permission to deny teleport request"
    default: op
  vitaltpa.delay.bypass:
    description: "Permission to bypass delay"
    default: op
  vitaltpa.tpcancel:
    description: "Permission to cancel a request"
    default: op